swagger: "2.0"
info:
  description: "This is the API for Acme AP Fatura Service"
  version: "1.0.0"
  title: "Acme AP Fatura Service"
  contact:
    email: "alexandre.zanelatto@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "fatura.acme.com.br"
basePath: "/v1"
tags:
- name: "faturas"
  description: "Everything about your Faturas"
schemes:
- "https"
- "http"
paths:
  /faturas:
    post:
      tags:
      - "faturas"
      summary: "Create a new fatura"
      description: ""
      operationId: "gerarFatura"
      consumes:
      - "application/json"
      produces:
      - "application/xml"
      parameters:
      - in: "body"
        name: "body"
        description: "Fatura object that needs to be added to the Fatura database"
        required: true
        schema:
          $ref: "#/definitions/Fatura"
      responses:
        "404":
          description: "Bad Request"
      security:
      - acme_auth:
        - "write:faturas"
        - "read:faturas"
    get:
      tags:
      - "faturas"
      summary: "Finds all faturas"
      operationId: "getAllFaturas"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Fatura"
      security:
      - acme_auth:
        - "read:faturas"
  /faturas/cpf/{cpf}:
    get:
      tags:
      - "faturas"
      summary: "Find Faturas by CPF"
      operationId: "getFaturasPorCPF"
      produces:
      - "application/json"
      parameters:
      - name: "cpf"
        in: "path"
        description: "CPF of the desired faturas to find"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Fatura"
        "400":
          description: "Invalid cpf value"
      security:
      - acme_auth:
        - "read:faturas"
  /faturas/{codigo}:
    get:
      tags:
      - "faturas"
      summary: "Find Fatura by Codigo"
      operationId: "getFatura"
      produces:
      - "application/json"
      parameters:
      - name: "codigo"
        in: "path"
        description: "Codigo of the desired fatura to find"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "object"
        "400":
          description: "Invalid codigo value"
      security:
      - acme_auth:
        - "read:faturas"
securityDefinitions:
  acme_auth:
    type: "oauth2"
    authorizationUrl: "http://auth.acme.com.br/oauth"
    flow: "implicit"
    scopes:
      write:faturas: "modify faturas in your account"
      read:faturas: "read your faturas"
definitions:
  Fatura:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      instalacaoId:
        type: "integer"
        format: "int64"
      codigo:
        type: "string"
      dataLeitura:
        type: "string"
      dataVencimento:
        type: "string"
      numeroLeitura:
        type: "integer"
        format: "int64"
      valorConta:
        type: "number"