swagger: "2.0"
info:
  description: "This is the API for Acme AP Instalação Service"
  version: "1.0.0"
  title: "Acme AP Instalação Service"
  contact:
    email: "alexandre.zanelatto@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "instalacao.acme.com.br"
basePath: "/v1"
tags:
- name: "instalacoes"
  description: "Everything about your Instalações"
schemes:
- "https"
- "http"
paths:
  /instalacoes:
    post:
      tags:
      - "instalacoes"
      summary: "Create a new instalação"
      operationId: "cadastrarInstalacao"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Instalação object that needs to be added to the Instalação database"
        required: true
        schema:
          $ref: "#/definitions/Instalacao"
      responses:
        "404":
          description: "Bad Request"
      security:
      - acme_auth:
        - "write:instalacoes"
        - "read:instalacoes"
    get:
      tags:
      - "instalacoes"
      summary: "Finds all instalacoes"
      operationId: "getAllInstalacoes"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Instalacao"
      security:
      - acme_auth:
        - "read:instalacoes"
  /instalacoes/cpf/{cpf}:
    get:
      tags:
      - "instalacoes"
      summary: "Find instalacoes by CPF"
      operationId: "getInstalacaoPorCPF"
      produces:
      - "application/json"
      parameters:
      - name: "cpf"
        in: "path"
        description: "CPF of the desired instalacoes to find"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Instalacao"
        "400":
          description: "Invalid cpf value"
      security:
      - acme_auth:
        - "read:instalacoes"
  /instalacoes/{codigo}:
    get:
      tags:
      - "instalacoes"
      summary: "Find Instalacao by Codigo"
      operationId: "getInstalacao"
      produces:
      - "application/json"
      parameters:
      - name: "codigo"
        in: "path"
        description: "Codigo of the desired Instalacao to find"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "object"
        "400":
          description: "Invalid codigo value"
      security:
      - acme_auth:
        - "read:instalacoes"
securityDefinitions:
  acme_auth:
    type: "oauth2"
    authorizationUrl: "http://auth.acme.com.br/oauth"
    flow: "implicit"
    scopes:
      write:instalacoes: "modify instalacoes in your account"
      read:instalacoes: "read your instalacoes"
definitions:
  Endereco:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      logradouro:
        type: "string"
      numero:
        type: "integer"
        format: "int64"
      bairro:
        type: "string"
      cidade:
        type: "string"
      uf:
        type: "string"
  Instalacao:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      clienteId:
        type: "integer"
        format: "int64"
      enderecoInstalacao:
        $ref: "#/definitions/Endereco"
      listaFaturaId:
        type: "array"
        items:
          type: "integer"
          format: "int64"
      codigo:
        type: "string"
      dataInstalacao:
        type: "integer"
        format: "int64"